apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dw-eks-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2

vpc:
  cidr: 10.10.0.0/16
  autoAllocateIPv6: false
  # disable public access to endpoint and only allow private access
  clusterEndpoints:
    publicAccess: false
    privateAccess: true
  nat:
    gateway: Single

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: microservice

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
    logRetentionInDays: 60
